[package]
name = "skibidibi-git-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[features]
default = []
microsoft-store = []

[build-dependencies]
tauri-build.workspace = true

[dependencies]
app-domain.workspace = true
app-store.workspace = true
github-client.workspace = true
repo-runtime.workspace = true
secret-store.workspace = true
serde.workspace = true
serde_json.workspace = true
tauri.workspace = true
tauri-plugin-dialog.workspace = true
tauri-plugin-opener.workspace = true
tauri-plugin-updater.workspace = true
tempfile.workspace = true
tokio.workspace = true
url.workspace = true
uuid.workspace = true
zeroize.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"
